language: generic 

cache:
    directories:
    - ~/toolchain
    - ~/src

before_install:
install:
    # check if there's an update
    - make check_latest
    # build updated tools
    - make ci-deps

#    # z3
#    - cd $HOME
#    - git clone https://github.com/Z3Prover/z3.git z3
#    - cd z3
#    - python scripts/mk_make.py
#    - cd build
#    - make -j2
#    - sudo make install

script:
    - cd $TRAVIS_BUILD_DIR
    - ls
    - PATH=~/toolchain/bin:$PATH make test

notifications:
  email:
    on_success: change
    on_failure: change

